# Declare variables to be passed into your templates.
image:
  repository: 626604290616.dkr.ecr.us-east-1.amazonaws.com/prod-univision-fe-k8s
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetUtilization: 50

pdb:
  maxUnavailable: 1

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 2000m
    memory: 1024Mi

config_map: {}
nodeSelector: {}
tolerations: []
affinity: {}

secret:
  enabled: false
# name:

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
