export default {
  tudn: {
    prod: 'https://www.tudn.com',
    integration: 'https://uat.tudn.com',
    qa: 'https://qa.tudn.com',
    uat2: 'https://uat.tudn.com',
    performance: 'https://performance.tudn.com',
  },
  univision: {
    prod: 'https://www.univision.com',
    integration: 'https://univision-fe-integration.k8s.dev-univision.com',
    qa: 'https://qa.x.univision.com',
    uat2: 'https://uat2.x.univision.com',
    performance: 'https://performance.univision.com',
  },
  prendetv: {
    prod: 'https://performance.univision.com',
    integration: 'https://performance.univision.com',
    qa: 'https://performance.univision.com',
    uat2: 'https://performance.univision.com',
    performance: 'https://performance.univision.com',
  },
  delicioso: {
    prod: 'https://www.delicioso.com.br',
    integration: 'https://int.delicioso.com.br',
    qa: 'https://uat.delicioso.com.br',
    uat2: 'https://uat.delicioso.com.br',
    performance: 'https://performance.delicioso.com.br',
  },
  mulher: {
    prod: 'https://www.mulher.com.br',
    integration: 'https://int.mulher.com.br',
    qa: 'https://uat.mulher.com.br',
    uat2: 'https://uat.mulher.com.br',
    performance: 'https://performance.mulher.com.br',
  },
  tasaudavel: {
    prod: 'https://www.tasaudavel.com.br',
    integration: 'https://int.tasaudavel.com.br',
    qa: 'https://uat.tasaudavel.com.br',
    uat2: 'https://uat.tasaudavel.com.br',
    performance: 'https://performance.tasaudavel.com.br',
  },
  zappeando: {
    prod: 'https://www.zappeando.com.br',
    integration: 'https://int.zappeando.com.br',
    qa: 'https://uat.zappeando.com.br',
    uat2: 'https://uat.zappeando.com.br',
    performance: 'https://performance.zappeando.com.br',
  },
  lasestrellas: {
    prod: 'https://www.lasestrellas.tv',
    integration: 'https://uat.lasestrellas.tv',
    qa: 'https://qa.lasestrellas.tv',
    uat2: 'https://uat.lasestrellas.tv',
    performance: 'https://performance.lasestrellas.tv',
  },
  distritocomedia: {
    prod: 'https://www.distritocomedia.com',
    integration: 'https://int.distritocomedia.com',
    qa: 'https://uat.distritocomedia.com',
    uat2: 'https://uat.distritocomedia.com',
    performance: 'https://performance.distritocomedia.com',
  },
  televisa: {
    prod: 'https://www.televisa.com',
    integration: 'https://int.televisa.com',
    qa: 'https://uat.televisa.com',
    uat2: 'https://uat.televisa.com',
    performance: 'https://performance.televisa.com',
  },
  elnu9ve: {
    prod: 'https://www.elnu9ve.com',
    integration: 'https://int.elnu9ve.com',
    qa: 'https://uat.elnu9ve.com',
    uat2: 'https://uat.elnu9ve.com',
    performance: 'https://performance-elnu9ve.televisa.com/',
  },
  unicable: {
    prod: 'https://www.unicable.com',
    integration: 'https://int.unicable.com',
    qa: 'https://uat.unicable.com',
    uat2: 'https://uat.unicable.tv',
    performance: 'https://performance.unicable.tv',
  },
  telehit: {
    prod: 'https://www.telehit.com',
    integration: 'https://int.telehit.com',
    qa: 'https://uat.telehit.com',
    uat2: 'https://uat.telehit.com',
    performance: 'https://performance.telehit.com',
  },
  losbingers: {
    prod: 'https://www.losbingers.com',
    integration: 'https://int.losbingers.com',
    qa: 'https://uat.losbingers.com',
    uat2: 'https://uat.losbingers.com',
    performance: 'https://performance.losbingers.com',
  },
  canal5: {
    prod: 'https://www.canal5.com',
    integration: 'https://int.canal5.com',
    qa: 'https://uat.canal5.com',
    uat2: 'https://uat.canal5.com',
    performance: 'https://performance-canal5.televisa.com',
  },
  bandamax: {
    prod: 'https://www.bandamax.tv',
    integration: 'https://int.bandamax.tv',
    qa: 'https://uat.bandamax.tv',
    uat2: 'https://uat.bandamax.tv',
    performance: 'https://performance.bandamax.tv',
  },
  lcdlf: {
    prod: 'https://www.lacasadelosfamososmexico.tv',
    integration: 'https://int.lacasadelosfamososmexico.tv',
    qa: 'https://uat.lacasadelosfamososmexico.tv',
    uat2: 'https://uat.lacasadelosfamososmexico.tv',
    performance: 'https://performance.lacasadelosfamososmexico.tv',
  },
};

export const contentDomains = {
  tudn: {
    prod: 'https://www.tudn.com',
    integration: 'https://uat.tudn.com',
    qa: 'https://qa.tudn.com',
    uat2: 'https://uat.tudn.com',
    performance: 'https://performance.tudn.com',
  },
  univision: {
    prod: 'https://www.univision.com',
    integration: 'https://univision-fe-integration.k8s.dev-univision.com',
    qa: 'https://qa.x.univision.com',
    uat2: 'https://uat2.x.univision.com',
    performance: 'https://performance.univision.com',
  },
  prendetv: {
    prod: 'https://www.prende.tv',
    integration: 'https://dev.prende.tv',
    qa: 'https://dev.prende.tv',
    uat2: 'https://uat.prende.tv',
    performance: 'https://dev.prende.tv',
  },
  delicioso: {
    prod: 'https://www.delicioso.com.br',
    integration: 'https://int.delicioso.com.br',
    qa: 'https://uat.delicioso.com.br',
    uat2: 'https://uat.delicioso.com.br',
    performance: 'https://performance.delicioso.com.br',
  },
  mulher: {
    prod: 'https://www.mulher.com.br',
    integration: 'https://int.mulher.com.br',
    qa: 'https://uat.mulher.com.br',
    uat2: 'https://uat.mulher.com.br',
    performance: 'https://performance.mulher.com.br',
  },
  tasaudavel: {
    prod: 'https://www.tasaudavel.com.br',
    integration: 'https://int.tasaudavel.com.br',
    qa: 'https://uat.tasaudavel.com.br',
    uat2: 'https://uat.tasaudavel.com.br',
    performance: 'https://performance.tasaudavel.com.br',
  },
  zappeando: {
    prod: 'https://www.zappeando.com.br',
    integration: 'https://int.zappeando.com.br',
    qa: 'https://uat.zappeando.com.br',
    uat2: 'https://uat.zappeando.com.br',
    performance: 'https://performance.zappeando.com.br',
  },
  lasestrellas: {
    prod: 'https://www.lasestrellas.tv',
    integration: 'https://uat.lasestrellas.tv',
    qa: 'https://qa.lasestrellas.tv',
    uat2: 'https://uat.lasestrellas.tv',
    performance: 'https://performance.lasestrellas.tv',
  },
  distritocomedia: {
    prod: 'https://www.distritocomedia.com',
    integration: 'https://int.distritocomedia.com',
    qa: 'https://uat.distritocomedia.com',
    uat2: 'https://uat.distritocomedia.com',
    performance: 'https://performance.distritocomedia.com',
  },
  televisa: {
    prod: 'https://www.televisa.com',
    integration: 'https://int.televisa.com',
    qa: 'https://uat.televisa.com',
    uat2: 'https://uat.televisa.com',
    performance: 'https://performance.televisa.com',
  },
  elnu9ve: {
    prod: 'https://www.elnu9ve.com',
    integration: 'https://int.elnu9ve.com',
    qa: 'https://uat.elnu9ve.com',
    uat2: 'https://uat.elnu9ve.com',
    performance: 'https://performance-elnu9ve.televisa.com/',
  },
  unicable: {
    prod: 'https://www.unicable.com',
    integration: 'https://int.unicable.com',
    qa: 'https://uat.unicable.com',
    uat2: 'https://uat.unicable.com',
    performance: 'https://performance.unicable.tv',
  },
  telehit: {
    prod: 'https://www.telehit.com',
    integration: 'https://int.telehit.com',
    qa: 'https://uat.telehit.com',
    uat2: 'https://uat.telehit.com',
    performance: 'https://performance.telehit.com',
  },
  losbingers: {
    prod: 'https://www.losbingers.com',
    integration: 'https://int.losbingers.com',
    qa: 'https://uat.losbingers.com',
    uat2: 'https://uat.losbingers.com',
    performance: 'https://performance.losbingers.com',
  },
  canal5: {
    prod: 'https://www.canal5.com',
    integration: 'https://int.canal5.com',
    qa: 'https://uat.canal5.com',
    uat2: 'https://uat.canal5.com',
    performance: 'https://performance-canal5.televisa.com',
  },
  bandamax: {
    prod: 'https://www.bandamax.tv',
    integration: 'https://int.bandamax.tv',
    qa: 'https://uat.bandamax.tv',
    uat2: 'https://uat.bandamax.tv',
    performance: 'https://performance.bandamax.tv',
  },
  lcdlf: {
    prod: 'https://www.lacasadelosfamososmexico.tv',
    integration: 'https://int.lacasadelosfamososmexico.tv',
    qa: 'https://uat.lacasadelosfamososmexico.tv',
    uat2: 'https://uat.lacasadelosfamososmexico.tv',
    performance: 'https://performance.lacasadelosfamososmexico.tv',
  },
};
