
version: 2.1
          

jobs:
  run-tests:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: "echo environment variables from org-global context"
          command: echo $AWS_ACCESS_KEY_ID





workflows:
  version: 2
  build_and_test:
    jobs:
      - run-tests:
        context: serverless-webapp-dev
        fiilter:
          branches:
            only:
              - feat/performance-mirrror
