import { ADVERTISING } from '@univision/shared-components/dist/constants/labelTypes';
import {
  ARTICLE,
  SLIDESHOW,
  VIDEO,
  LIVE_BLOG,
  LIVE_STREAM,
  SOCCER_MATCH,
  EXTERNAL_CONTENT_PROMO,
  EXTERNAL_LINK,
  PERSON,
  SOCCER_PERSON,
} from '@univision/fe-commons/dist/constants/contentTypes';
import {
  LOADING,
} from '@univision/fe-commons/dist/constants/status';
import { HOROSCOPE } from '@univision/fe-commons/dist/constants/pageCategories';

import {
  VIDEO_INLINE_TYPE,
} from '../../constants';

export default {
  [ADVERTISING]: {
    showTitle: true,
    showBadge: true,
    showCTA: true,
    autoHeight: true,
    positionAbsolute: false,
    target: '_self',
    useExplicitNavigation: true,
    hasActionBar: false,
  },
  [ARTICLE]: {
    showTitle: true,
    showBadge: true,
    showCTA: true,
    autoHeight: true,
    positionAbsolute: false,
    target: '_self',
    useExplicitNavigation: true,
    hasActionBar: true,
  },
  [SLIDESHOW]: {
    showTitle: true,
    showBadge: true,
    showCTA: true,
    autoHeight: true,
    positionAbsolute: true,
    target: '_self',
    useExplicitNavigation: true,
    hasActionBar: true,
  },
  [VIDEO]: {
    showTitle: true,
    showBadge: true,
    showCTA: true,
    autoHeight: false,
    positionAbsolute: true,
    target: '_self',
    useExplicitNavigation: true,
    hasActionBar: true,
  },
  [LIVE_BLOG]: {
    showTitle: true,
    showBadge: true,
    showCTA: true,
    autoHeight: true,
    positionAbsolute: true,
    target: '_self',
    useExplicitNavigation: true,
    hasActionBar: true,
  },
  [LIVE_STREAM]: {
    showTitle: true,
    showBadge: true,
    showCTA: false,
    autoHeight: true,
    positionAbsolute: false,
    target: '_self',
    useExplicitNavigation: true,
    hasActionBar: true,
  },
  [LOADING]: {
    hideContent: true,
    hasActionBar: false,
  },
  [SOCCER_MATCH]: {
    showTitle: true,
    showBadge: false,
    showCTA: false,
    autoHeight: false,
    positionAbsolute: true,
    target: '_self',
    useExplicitNavigation: true,
    hasActionBar: true,
  },
  [VIDEO_INLINE_TYPE]: {
    showTitle: false,
    showBadge: true,
    showCTA: false,
    autoHeight: false,
    positionAbsolute: true,
    target: '_self',
    useExplicitNavigation: true,
    hasActionBar: true,
  },
  [EXTERNAL_CONTENT_PROMO]: {
    showTitle: true,
    showBadge: false,
    showCTA: false,
    autoHeight: true,
    positionAbsolute: true,
    target: '_blank',
    useExplicitNavigation: false,
    hasActionBar: false,
  },
  [EXTERNAL_LINK]: {
    showTitle: true,
    showBadge: false,
    showCTA: false,
    autoHeight: true,
    positionAbsolute: true,
    target: '_blank',
    useExplicitNavigation: false,
    hasActionBar: false,
  },
  [PERSON]: {
    hasActionBar: false,
  },
  [SOCCER_PERSON]: {
    hasActionBar: false,
    hideContent: true,
  },
  [HOROSCOPE]: {
    showTitle: true,
    showBadge: false,
    showCTA: true,
    autoHeight: false,
    positionAbsolute: true,
    target: '_self',
    useExplicitNavigation: true,
    hideContent: false,
    hasActionBar: true,
  },
  default: {
    hideContent: true,
    hasActionBar: true,
  },
};
