image:
  repository: 626604290616.dkr.ecr.us-east-1.amazonaws.com/prod-univision-fe-k8s
  tag: latest
  pullPolicy: IfNotPresent

hpa:
  minReplicas: 1
  maxReplicas: 100
  targetUtilization: 80

pdb:
  maxUnavailable: 1

resources:
  limits:
    cpu: 1500m
    memory: 2048Mi
  requests:
    cpu: 600m
    memory: 500Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-external
  paths:
    - /
  hosts:
    - univision-fe-integration.k8s.dev-univision.com
  tls:
    - univision-fe-integration.k8s.dev-univision.com

vanityingress:
  enabled: false

config_map:
  CDN_URL: https://univision-fe-integration.k8s.dev-univision.com
  CMS_API_URL: https://uat2.x.univision.com
  DD_ENV: dev
  DD_LOGS_INJECTION: true
  DD_SERVICE_NAME: web-app
  DD_TRACE_AGENT_HOSTNAME: datadog-statsd.datadog
  DD_TRACE_AGENT_PORT: 8126
  DD_TRACE_DEBUG: true
  DD_TRACE_ENABLED: false
  DEPLOY_ENV: test
  GRAPHQL_API_URL: https://int-graphql.dev-univision.com
  NODE_ENV: production
  MULTI_DOMAIN_DISABLED: false
  SPA_MONITORING_ENABLED: false
  SPORT_API_URL: https://sports-api-dev.univision.com
  SSO_IFRAME_URL: https://univision-fe-integration.k8s.dev-univision.com/sso-iframe
  VIDEO_HUB_ENV: qa

secret:
  enabled: true
  name: univision-fe

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
