image:
  repository: 626604290616.dkr.ecr.us-east-1.amazonaws.com/prod-univision-fe-k8s
  tag: latest
  pullPolicy: IfNotPresent

hpa:
  minReplicas: 1
  maxReplicas: 100
  targetUtilization: 80

pdb:
  maxUnavailable: 1

resources:
  limits:
    cpu: 1500m
    memory: 2048Mi
  requests:
    cpu: 600m
    memory: 500Mi

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-external
  paths:
    - /
  hosts:
    - univision-fe-qa.k8s.dev-univision.com
  tls:
    - univision-fe-qa.k8s.dev-univision.com

vanityingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/waf-acl-id: bbdced31-c4eb-4e35-8e17-3c57d55777d8
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:127705864914:certificate/478539b5-2114-4dfe-bd23-d6d51ed4a459"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
  paths:
    - /*

config_map:
  AWS_S3_ASSETS_BUCKET: webapp-static-prod.univision.com
  # CDN_URL: This gets set on /packages/tools/ci/environmentEnvVars.json as it's to be set when the application builds.
  # CDN_URL_OVERRIDE: Use this if you need a value different from what gets set for CDN_URL environmentEnvVars.json for the branch tied to this env.
  CMS_API_URL: https://qa.x.univision.com
  DD_ENV: dev
  DD_LOGS_INJECTION: false
  DD_SERVICE_NAME: web-app
  DD_TRACE_AGENT_HOSTNAME: datadog-statsd.datadog
  DD_TRACE_AGENT_PORT: 8126
  DD_TRACE_DEBUG: false
  DD_TRACE_ENABLED: false
  DEPLOY_ENV: test
  GRAPHQL_API_URL: https://uat-graphql.dev-univision.com
  NODE_ENV: production
  MULTI_DOMAIN_DISABLED: true
  SPORT_API_URL: https://sports-api-dev.univision.com
  SSO_IFRAME_URL: https://qa.x.univision.com/sso-iframe
  VIDEO_HUB_ENV: qa

secret:
  enabled: true
  name: univision-fe

strategy:
  rollingUpdate:
    maxSurge: 40%
    maxUnavailable: 10%
