apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "univision-fe.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "univision-fe.name" . }}
    helm.sh/chart: {{ include "univision-fe.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "univision-fe.fullname" . }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.hpa.targetUtilization }}
        type: Utilization
