{{- if .Values.vanityingress.enabled -}}
{{- $fullName := include "univision-fe.fullname" . -}}
{{- $ingressPaths := .Values.vanityingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-vanity
  labels:
    app.kubernetes.io/name: {{ include "univision-fe.name" . }}
    helm.sh/chart: {{ include "univision-fe.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.vanityingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.vanityingress.tls }}
  tls:
  {{- range .Values.vanityingress.tls }}
    - hosts:
        - {{ . | quote }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
  {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
