import * as categories from '../../../constants/pageCategories';
// eslint-disable-next-line import/no-cycle
import { matchTagUri, matchPageUri, matchExactPageUri } from './matchers';

export default {
  [categories.ACCION_EJECUTIVA]: [matchTagUri('/temas/accion-ejecutiva'), matchTagUri('/noticias/accion-ejecutiva'), matchTagUri('/noticias/politica/accion-ejecutiva')],
  [categories.AMEXICA]: [matchTagUri('/noticias/amexica')],
  [categories.AUTOS]: [matchTagUri('/temas/autos'), matchTagUri('/noticias/autos'), matchTagUri('/carros')],
  [categories.CENSO_2020]: [
    matchPageUri('/cuentaconmigo'),
    matchPageUri('/censo2020'),
    matchPageUri('/noticias/especiales/cuenta-conmigo-participa-en-el-censo-2020'),
    matchPageUri('/univision/censo-2020'),
  ],
  [categories.CITYLAB]: [matchTagUri('/noticias/citylab-latino')],
  [categories.CONTIGO]: [matchTagUri('/noticias/especiales/contigo')],
  [categories.CORONAVIRUS]: [matchPageUri('/noticias/coronavirus'), matchPageUri('/coronavirus')],
  [categories.DESTINO2020_VOTA_CONMIGO]: [matchPageUri('/destino-vota-conmigo')],
  [categories.DETECTOR_MENTIRAS]: [matchTagUri('/temas/detector-de-mentiras'), matchTagUri('/noticias/detector-de-mentiras')],
  [categories.DOCUMENTALES]: [matchTagUri('/temas/documentales'), matchTagUri('/temas/documentales-univision'), matchTagUri('/noticias/documentales')],
  [categories.ELECCIONES_MEXICO_2018]: [matchTagUri('/temas/elecciones-mexico-2018'), matchTagUri('/noticias/elecciones-mexico-2018')],
  [categories.ELECCIONES_2020]: [matchTagUri('/noticias/elecciones-en-eeuu-2020'), matchPageUri('/noticias/elecciones-en-eeuu-2020')],
  [categories.ELECCIONES_2022]: [matchTagUri('/noticias/politica/elecciones-en-eeuu-2022'), matchPageUri('/noticias/politica/elecciones-en-eeuu-2022')],
  [categories.HEALTHI_NATION]: [matchPageUri('/noticias/healthination')],
  [categories.POLITICA]: [matchPageUri('/noticias/politica')],
  [categories.INMIGRACION]: [matchTagUri('/temas/inmigracion'), matchTagUri('/noticias/inmigracion')],
  [categories.FUERTES_JUNTOS]: [matchTagUri('/noticias/salud/fuertes-juntos')],
  [categories.MEXICO]: [matchTagUri('/temas/mexico'), matchTagUri('/noticias/mexico')],
  [categories.MI_SALUD_MI_DECISION]: [matchTagUri('/noticias/mi-salud-mi-decision'), matchPageUri('/noticias/mi-salud-mi-decision')],
  [categories.NEWS]: [
    matchTagUri('/noticias/especiales/contigo'),
    matchTagUri('/especiales/seguridad-online'),
    matchTagUri('/noticias/especiales/act'),
    matchTagUri('/noticias/especiales/la-huella-digital'),
    matchTagUri('/noticias/especiales'),
    matchExactPageUri('/local'),
    matchTagUri('/especiales/seguridad-online'),
    matchTagUri('/noticias/especiales/act'),
    matchTagUri('/noticias/especiales/la-huella-digital'),
  ],
  [categories.PLANETA]: [matchTagUri('/temas/planeta'), matchTagUri('/temas/medio-ambiente'), matchTagUri('/noticias/planeta'), matchTagUri('/noticias/medio-ambiente')],
  [categories.REPORTE_ODIO]: [
    matchPageUri('/noticias/el-reporte-del-odio'),
    matchPageUri('/noticias/sobre-este-proyecto-el-reporte-del-odio'),
    matchPageUri('/test/denuncia-tu-caso-openpage'),
    matchPageUri('/noticias/incidentes-de-odio/mapa-interactivo-monitoreamos-los-incidentes-de-odio-desde-la-victoria-de-trump'),
    matchPageUri('/noticias/racismo/guia-como-defenderte-y-denunciar-el-odio-racial'),
  ],
  [categories.RETO28]: [matchTagUri('/noticias/reto-28')],
  [categories.SEGUNDA_OPORTUNIDAD]: [matchTagUri('/segunda-oportunidad')],
  [categories.SECOND_CHANCES]: [matchTagUri('/second-chances')],
  [categories.SILICON_VALLEY]: [matchTagUri('/noticias/silicon-valley-community-foundation'), matchPageUri('/noticias/silicon-valley-community-foundation')],
  [categories.TE_EXPLICAMOS]: [
    matchTagUri('/noticias/especiales/te-explicamos'),
    matchTagUri('/noticias/educacion/te-explicamos'),
    matchTagUri('/noticias/inmigracion/te-explicamos'),
    matchTagUri('/noticias/fenomenos-naturales/te-explicamos'),
    matchTagUri('/noticias/educacion/te-explicamos/respuesta'),
    matchTagUri('/noticias/inmigracion/te-explicamos/respuesta'),
    matchTagUri('/noticias/fenomenos-naturales/te-explicamos/respuesta'),
  ],
  [categories.UNIDOS_CONTRA_CORONAVIRUS]: [matchPageUri('/unidos')],
  [categories.UNIDOS_SOMOS_UNO]: [
    matchPageUri('/unidossomosuno'),
    matchPageUri('/unidos-somos-uno'),
    matchPageUri('/univision/unidossomosuno'),
    matchPageUri('/univision/unidos-somos-uno'),
  ],
  [categories.UNIVISION_NEWS]: [matchTagUri('/tag/news-in-english'), matchTagUri('/univision-news')],
};
