export const CATEGORIES = [
  'Legal',
  'Health',
  'Home',
  'Business',
];

export const ALLSUBCATEGORIES = {
  Legal: [
    'Personal Injury',
    'Immigration',
    'Criminal',
    'Workers Comp/ Labor Law',
    'Lemon Law',
    'Bankruptcy',
    'Family Law',
    'Tax & Financial',
    'Civil Rights',
  ],
  Health: [
    'Hospitals',
    'Health Insurance',
    'Dentists',
    'Cosmetic',
    'Pediatrics',
    'Eye Care',
    'Hearing',
    'Home Health Services',
    'Medical Equipment',
    'Chiropractic',
    'Weight Loss',
    'Fitness',
    'Men’s Health',
    'Women’s Health',
    'Mental Health',
    'Urgent Care',
    'Pain Care',
    'Allergy',
  ],
  Home: [
    'Home insurance',
    'Energy/Gas',
    'Furniture stores',
    'Real Estate',
    'Home improvement',
    'Construction',
    'Electrician',
    'Plumber',
    'Painter',
    'Pool Maintenance',
    'Weather Preparedness',
    'Lawn & Garden',
    'Outdoor Living',
    'Home Security',
  ],
  Business: [
    'Taxes',
    'Marketing',
    'Managing Covid',
    'Legal',
    'Recruitment',
    'Insurance',
    'Human Resources',
    'Banking/Financial',
  ],
};

export const CITIES = [
  'Area de la Bahia',
  'Arizona',
  'Atlanta',
  'Austin',
  'Bakersfield',
  'Chicago',
  'Dallas',
  'Fresno',
  'Houston',
  'Los Angeles',
  'Miami',
  'Noth California',
  'Nueva York',
  'Orlando',
  'Philadelphia',
  'Puerto Rico',
  'Sacramento',
  'Salt Lake City',
  'San Antonio',
  'Tampa Bay',
  'Washington DC',
];

export const MARKET = [
  'San Francisco',
  'Arizona',
  'Atlanta',
  'Austin',
  'Bakersfield',
  'Chicago',
  'Dallas Ft. Worth',
  'Fresno',
  'Houston',
  'Los Angeles',
  'Miami',
  'Noth California',
  'Nueva York',
  'Orlando',
  'Philadelphia',
  'Puerto Rico',
  'Sacramento',
  'Salt Lake City',
  'San Antonio',
  'Tampa Bay',
  'Washington',
];

export const BAHIA = 'Area de la Bahia';
export const SF = 'San Francisco';
